'use client';

import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto px-6 py-20 animate-fade-in">
      <div className="flex items-center gap-4 mb-12">
        <Link href="/feed" className="flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-muted-foreground hover:text-foreground transition-all">
          <span className="w-8 h-[1px] bg-border" />
          Back to Archive
        </Link>
      </div>

      <header className="mb-20">
        <h1 className="text-5xl md:text-7xl font-black tracking-tighter uppercase mb-6">
          Terms of Sync
        </h1>
        <p className="text-xl font-medium text-muted-foreground">
          Establishing the binary contract between Resident and Network.
        </p>
      </header>

      <section className="prose prose-zinc prose-lg max-w-none space-y-12">
        <div>
          <h2 className="text-xs font-black uppercase tracking-[0.3em] mb-4">01. Content Authority</h2>
          <p className="text-zinc-600 leading-relaxed font-body">
            You own the narratives you publish on LUMEN. By syncing your content to our network, you grant us a non-exclusive license to archive and display your logs as part of the global LUMEN feed.
          </p>
        </div>

        <div>
           <h2 className="text-xs font-black uppercase tracking-[0.3em] mb-4">02. Conduct Protocol</h2>
           <p className="text-zinc-600 leading-relaxed font-body">
             LUMEN is a space for radical thinking, but binary respect is required. Harassment, malware injection, or identity theft will result in an immediate de-synchronization from the network.
           </p>
        </div>

        <div>
           <h2 className="text-xs font-black uppercase tracking-[0.3em] mb-4">03. Automated Assistance</h2>
           <p className="text-zinc-600 leading-relaxed font-body">
             Our AI tools are provided "as-is" to assist in your creative flow. LUMEN is not liable for hallucinations, code errors, or narrative contradictions generated by these automated sub-processes.
           </p>
        </div>

        <div>
           <h2 className="text-xs font-black uppercase tracking-[0.3em] mb-4">04. Protocol Termination</h2>
           <p className="text-zinc-600 leading-relaxed font-body">
             We reserve the right to modify or terminate access to the network at our discretion if the Terms of Sync are breached.
           </p>
        </div>
      </section>

      <footer className="mt-32 pt-20 border-t border-border">
         <p className="text-[10px] font-black text-muted-foreground uppercase tracking-widest leading-loose">
          ESTABLISHED: APRIL 2026
          <br />
          LEGAL AUTHORITY: LUMEN ARCHIVE CORE
         </p>
      </footer>
    </div>
  );
}
